version: "3.8"

services:

  experiments_pg_db:
    container_name: experiments_pg_db
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}

  experiments_pgadmin:
    container_name: experiments_pgadmin
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_PASSWORD}
    ports:
      - 5050:80
    depends_on:
      - experiments_pg_db

  experiments_api:
      container_name: experiments_api
      build: .
#      command: bash -c "alembic upgrade head && uvicorn main:app --host 0.0.0.0 --port 8000 --reload"
      command: bash -c "python migrate_tables.py && uvicorn main:app --host 0.0.0.0 --port 8000 --reload"
      volumes:
        - .:/app
      ports:
        - 8000:8000
      depends_on:
        - experiments_pg_db
      restart: always